pipelines:
  dojo-init:
    group: dojo
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@git.ai-traders.com:dojo/dojo-init.git"
        branch: master
    stages:
      - test:
          clean_workspace: true
          jobs:
            build:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks test
      - release:
          clean_workspace: true
          jobs:
            build:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks release
