pipelines:
  dojo-init:
    group: dojo
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@git.ai-traders.com:dojo/dojo-init.git"
        branch: master
    stages:
      - test:
          clean_workspace: true
          jobs:
            test:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks test
      - release:
          clean_workspace: true
          secure_variables:
            GITHUB_TOKEN: "AES:9mQGklAskrmLBczL1b/UXQ==:u/Kt5dVTpXlDIOTN7ndS6SId01ryLQK+8OorJS7ZA8EECQvc04daQkLA+gRuzHNg"
          jobs:
            release:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - ./tasks release_gh
